### ISSUE TITLE
Visitors need an audio countdown to signal when they should start running

### ISSUE THREAD

**Issue by azuldev1** [cns-iu/xmacroscope#212]
Add audio to countdown clock for the run experience.

**Comment by bryankennedy** [comment]
Manuel and I just talked about this one.

The audio file limits some customizability that we built into the settings timer values. But since we think that most people are going to want to use the 3,2,1 Go countdown I don't think that that is an issue.

We actually have an audio file from the original SMM Run exhibit too that Manuel will work on implementing here.

**Comment by bryankennedy** [comment]
The audio countdown is working well now. We implemented the recordings that we used in the Sportsology exhibit.
