### ISSUE TITLE
Zip code entry looses 10-key layout on horizontal display

### ISSUE THREAD

**Issue by bryankennedy** [cns-iu/xmacroscope#235]
The zip code entry should look like a traditional 10-key layout, and it works right on a vertical display:
https://d.pr/i/ZXbRZQ

However, the key layout gets lost on the horizontal display.

**Comment by azuldev1** [comment]
@bryankennedy and @bherr2 I intentionally made the keypad layout change for the horizontal orientation. Keeping the traditional layout in horizontal orientation makes the form overflow. I could make the form three columns instead of two to keep the traditional keypad layout, but I think that would look at little off. Please feel free to way in.
