### ISSUE TITLE
Improve look and feel of dropzones

### ISSUE THREAD

**Issue by scimap** [cns-iu/xmacroscope#62]
@bherr2 commented on [Fri Feb 16 2018](https://github.com/cns-iu/aisl/issues/42)

**Comment by bryankennedy** [comment]
We talked about the drag and drop interface a bit in our weekly dev call today. @lecross acknowledged that there might be some usability issues here.

We also talked about how CNS should probably get the same ELO touchscreen hardware that we will be using in the exhibit so that they can physically test the touch and drag usability.

**Comment by bherr2** [comment]
Can you get us the ELO touchscreen model? Is it [Elo Touch 3243 32" LED](https://www.bhphotovideo.com/c/product/1280802-REG/elo_touch_e326202_3243l_32_led_open_frame.html?ap=y&gclid=EAIaIQobChMInemGuZa92wIVSIN-Ch0TBQqaEAkYASABEgJkNvD_BwE)?

**Comment by bryankennedy** [comment]
Yes, I just need to confirm with our hardware guy about the specific model. There are some differences in the touch capabilities on the different ones and I want to make sure we support multiple touches which might be useful at some point in the future.
